### ISSUE TITLE
布局方法抽象为交互组件

### ISSUE THREAD

**Issue by haiqinghao** [antvis/GraphInsight#2]
目前布局方法依赖左侧的布局切换方法。
![image](https://user-images.githubusercontent.com/76591446/178092246-247fdd82-7600-4e45-b535-aa4c494108e8.png)
希望将布局方法切换抽象为一个组件
这样可以在某个容器（例如“操作栏”）中加入这个组件，从而让构建的项目可以进行基本的布局切换。
建议
1、如果不在项目中暴露布局算法参数的话可以直接给出简单的切换交互组件
![image](https://user-images.githubusercontent.com/76591446/178092347-216c423b-99d2-4bf7-a370-116c58e3b108.png)
2、如果在项目中暴露布局算法参数的话可以参照图计算在侧边栏的方式
![image](https://user-images.githubusercontent.com/76591446/178092428-f99eaa79-0ee2-46d1-b7ca-c4c02745e3e7.png)

**Comment by pomelo-nwu** [comment]
@haiqinghao 感谢反馈！布局切换组件我们将在下个版本上线

**Comment by pomelo-nwu** [comment]
@haiqinghao 已经有「切换布局」资产了
