### ISSUE TITLE
筛选器中关于离散数据的展示

### ISSUE THREAD

**Issue by haiqinghao** [antvis/GraphInsight#3]
筛选器中目前对于离散数据的统计与展示是饼图
![image](https://user-images.githubusercontent.com/76591446/178095410-acb969be-cb2b-4413-aaa4-0b29609b992a.png)
建议
1、直接替换为条形图
饼图在展示类别数据中10个以上就不太友好
条形图可以展示更多类别，并且可以通过展开更多进行加载
![image](https://user-images.githubusercontent.com/76591446/178095466-91e080b6-2e1b-4fa5-a2ff-a4a9f6851747.png)

2、或者支持可以切换为条形图。
在这里增加切换菜单，可以切换不同图表
![image](https://user-images.githubusercontent.com/76591446/178095525-fa9ee6de-e93f-4d51-a150-15d4ae18b032.png)

**Comment by pomelo-nwu** [comment]
@haiqinghao 非常棒的建议，我们在下个版本优化，增加图表类型切换功能

**Comment by pomelo-nwu** [comment]
@haiqinghao 已经实现了
