### ISSUE TITLE
增加算法分析面板后页面白板

### ISSUE THREAD

**Issue by chinaxushi** [antvis/GraphInsight#4]
资产里选择算法分析面板后，在组件-操作栏中增加算法分析面板后，整个项目页面消失，是一个白板。这是BUG，还是哪里没操作对？现在导致原先项目也无法查看了。
![image](https://user-images.githubusercontent.com/30817644/178660815-0eb57e82-6c68-42a1-bd08-5d0f7b2096a0.png)

**Comment by chinaxushi** [comment]
没人遇到过？

https://user-images.githubusercontent.com/30817644/178887003-c4e9adf2-4ddd-49cf-bbd7-e0b8063acd5b.mp4

**Comment by pomelo-nwu** [comment]
@chinaxushi 晚些时候我看下

**Comment by pomelo-nwu** [comment]
@chinaxushi 我这边复现了，
![image](https://user-images.githubusercontent.com/10703060/178944942-ffcb00aa-97c3-4369-91b3-39dafc2e05a0.png)
原因是这个资产强依赖GraphScope引擎，目前对外的GI站点，暂不提供该引擎能力，所以这个资产晚些时候我会下线处理，给你造成不便，抱歉哈
