### ISSUE TITLE
创建项目时报错

### ISSUE THREAD

**Issue by luosc** [antvis/GraphInsight#40]
想请问一下，使用源代码在本地部署后，使用localhost登录时创建项目是正常的，但使用IP地址登录创建项目时报错，不知是什么原因？
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/25264928/203252088-182ab39c-17c4-46b4-a763-6e8c55b7ee14.png">

**Comment by pomelo-nwu** [comment]
@luosc 因为通过IP地址访问，代码判断不是LOCAL环境，详见： https://github.com/antvis/GraphInsight/blob/master/packages/gi-site/src/services/const.tsx#L8

**Comment by luosc** [comment]
> @luosc 因为通过IP地址访问，代码判断不是LOCAL环境，详见： https://github.com/antvis/GraphInsight/blob/master/packages/gi-site/src/services/const.tsx#L8

好的，谢谢

**Comment by pomelo-nwu** [comment]
@luosc 如果有帮助，还麻烦点个Star哈，你的鼓励是我们前行的动力

**Comment by luosc** [comment]
> @luosc 如果有帮助，还麻烦点个Star哈，你的鼓励是我们前行的动力

👌🏻
