### ISSUE TITLE
辐射布局多type类型节点渲染慢问题

### ISSUE THREAD

**Issue by zyh0yh** [antvis/GraphInsight#45]
面对多种type节点的渲染，节点数量在400，使用的辐射布局，渲染图很慢，而且渲染出来节点还会出现重叠的情况，这个该怎么去优化

**Comment by zyh0yh** [comment]
layout: {
        type: "radial",
        unitRadius: 800,
        preventOverlap: true,
        maxPreventOverlapIteration: 1000,
      },
同时也开启了节点防重叠

**Comment by pomelo-nwu** [comment]
@zyh0yh 是用的 G6 代码实现的吗

**Comment by zyh0yh** [comment]
> @zyh0yh 是用的 G6 代码实现的吗

是的，每次的渲染速度都在3-5分钟这样子

**Comment by zyh0yh** [comment]
`setNodes(nodes) {
      if (!nodes || nodes.length === 0) return [];
      let arr = nodes;
      arr.sort((a, b) => b.data.degrees - a.data.degrees);
      const ns = arr.map((node) => {
        this.setNodeType(node.data);
        let style = {
          ...node.data.style,
          fill: nodeTypeMap[node.data.ntype].color,
          stroke: nodeTypeMap[node.data.ntype].color,
        };
        node.data.cluster = node.data.labels[0];
        const stateStyles = {
          active: {
            fill: nodeTypeMap[node.data.ntype].color,
            stroke: nodeTypeMap[node.data.ntype].color,
            lineWidth: 4,
            opacity: 1,
          },
          inactive: {
            opacity: 0.05,
          },
          hover: {
            fill: "red",
            stroke: "#000",
            lineWidth: 1,
          },
        };
        return {
          type: nodeTypeMap[node.data.ntype].type,
          size: this.setNodeSize(node.data),
          ...node,
          style,
          stateStyles: stateStyles,
        };
      });
      return ns;
    },`
这是我设置节点类型的方法

**Comment by pomelo-nwu** [comment]
@zyh0yh 写个codesandbox复现下，我帮你艾特G6核心开发者

**Comment by zyh0yh** [comment]
> 

由于数据涉密，没办法进行网络的一个编写

**Comment by pomelo-nwu** [comment]
@zyh0yh 数据脱敏下，只写图结构

**Comment by zyh0yh** [comment]
> @zyh0yh 写个codesandbox复现下，我帮你艾特G6核心开发者

由于数据涉密，没办法进行网络的一个编写

> @zyh0yh 数据脱敏下，只写图结构

好的，写好之后需要怎么操作呢

**Comment by zyh0yh** [comment]
> @zyh0yh 地址贴的这里，我们排查下

好的，那可能需要明天晚一点才能进行了，非常感谢你的帮助，我会在贴好之后给您一个回复
