### ISSUE TITLE
创建任务失败,需要本地模式

### ISSUE THREAD

**Issue by TanLingxiao** [antvis/GraphInsight#47]
![f54577caeb9d6d15ba7280e7085b3d2](https://user-images.githubusercontent.com/8078355/204099903-97d00a56-97e5-4a5f-8b31-d0f2682307ee.png)

**Comment by BoyYangzai** [comment]
您好 方便提供一个复现分支吗

**Comment by TanLingxiao** [comment]
已解决，需要在本地模式运行

**Comment by pomelo-nwu** [comment]
@TanLingxiao https://github.com/antvis/GraphInsight/blob/master/packages/gi-site/src/services/const.tsx#L8
