### ISSUE TITLE
导出的离线html中，保存分享资产不可用

### ISSUE THREAD

**Issue by byew** [antvis/GraphInsight#53]
您好。
graphInsight的线上页面端，保存分享资产会正常跳转新页面。

但是在导出SDK-导出HTML生成的离线html页面，点 保存分享 没反应。

**Comment by pomelo-nwu** [comment]
@BoyYangzai 跟进下这个问题，应该应该是「保存分享」这个资产的设置问题

**Comment by BoyYangzai** [comment]
已解决，待 @pomelo-nwu 发包
