### ISSUE TITLE
graphinsight可以兼容在微信中展示吗或是非电脑端展示吗？

### ISSUE THREAD

**Issue by zchengzhong** [antvis/GraphInsight#58]

**Comment by zchengzhong** [comment]
比如把https://graphinsight.antgroup.com/  链接在微信中打开，大部分可以查看，但像点击图上的节点，无法弹出节点详情的面板，见下图：
![image](https://user-images.githubusercontent.com/2253700/205419961-b37cf97a-9076-488e-9c85-a17ebe2625c6.png)

**Comment by pomelo-nwu** [comment]
@zchengzhong 不支持移动端哦，毕竟很多交互都是PC上的交互，对屏幕展示尺寸也是有要求的。
