### ISSUE TITLE
antvis/gi-httpservice 版本问题 [README fix]

### ISSUE THREAD

**Issue by scarletfrank** [antvis/GraphInsight#60]
README里的Neo4j[使用文档](https://www.yuque.com/antv/gi/otnlbq2dc9q1f8gt#bWDFc)，版本写的是1.1.0
但我去[hub](https://hub.docker.com/r/antvis/gi-httpservice) 还没看到1.1.0，只有1.0.0

> 以及我本地配置的是阿里的镜像加速，好像拉取不到的样子...

以及关于GraphInsight部署方式我想问下，

1. Docker镜像里是所有资产都有了吗，我看文档里
> antvis/gi-httpservice：依赖 gshttpservice，提供连接 GS 引擎、Gremlin 查询、邻居扩展等图分析能力.

2. 我也看了下[01. 导出 GISDK](https://www.yuque.com/antv/gi/bw1fhv)，看了下【下载项目】导出的.txt，（【导出SDK】CodeSandbox选项，公司网不咋地访问不到）
> 该变量，记录的是用户在 GI 上使用的资产包信息（按需加载）GISDK会根据这些信息，动态请求 JS 和对应的 CSS 资源，每个资产包的信息如下

我想问假如项目里嵌入GISDK，资产包里的js，打包的时候加载的进来吗，因为最终环境是断网的

**Comment by pomelo-nwu** [comment]
- 「README里的Neo4j[使用文档](https://www.yuque.com/antv/gi/otnlbq2dc9q1f8gt#bWDFc)，版本写的是1.1.0」
这里是文档写错了，版本就是 1.0.0因为 gihttpservices 是重新命名的，版本号从1.0.0开始
- 「我本地配置的是阿里的镜像加速，好像拉取不到的样子」这个可以自定义镜像地址吧，在.npmrc
中修改
- 「Docker镜像里是所有资产都有了吗」docker镜像只打包nodeBFF层的一些东西，和分析资产无关系。源码地址：https://github.com/antvis/GraphInsight/tree/master/packages/gi-httpservice
- 「【导出SDK】CodeSandbox选项，公司网不咋地访问不到」codesandbox国内访问都得科学网络加速
- 「资产包里的js，打包的时候加载的进来吗，因为最终环境是断网的」：现在提供npm包里，可以按需加载使用，产物也可以打成一个bundle，这个你看「导出下载」选择第四个方式「npm方式」

**Comment by scarletfrank** [comment]
> * 「README里的Neo4j[使用文档](https://www.yuque.com/antv/gi/otnlbq2dc9q1f8gt#bWDFc)，版本写的是1.1.0」
>   这里是文档写错了，版本就是 1.0.0因为 gihttpservices 是重新命名的，版本号从1.0.0开始
> * 「我本地配置的是阿里的镜像加速，好像拉取不到的样子」这个可以自定义镜像地址吧，在.npmrc
>   中修改
> * 「Docker镜像里是所有资产都有了吗」docker镜像只打包nodeBFF层的一些东西，和分析资产无关系。源码地址：https://github.com/antvis/GraphInsight/tree/master/packages/gi-httpservice
> * 「【导出SDK】CodeSandbox选项，公司网不咋地访问不到」codesandbox国内访问都得科学网络加速
> * 「资产包里的js，打包的时候加载的进来吗，因为最终环境是断网的」：现在提供npm包里，可以按需加载使用，产物也可以打成一个bundle，这个你看「导出下载」选择第四个方式「npm方式」

哦哦好的，主要公司科学网络访问也不稳定，我回家仔细看看npm方式导出的产物。

没说清楚，我说的镜像是Docker的镜像源，不知道跟这个有没有联系

![image](https://user-images.githubusercontent.com/25702099/205567204-7e5b0f0c-0558-40d2-8900-e58ba9835568.png)

**Comment by pomelo-nwu** [comment]
@scarletfrank 对，docker 和 npm 的镜像源都可以设置

**Comment by scarletfrank** [comment]
- 我感觉今天网络问题太影响了， 也许回到家这个镜像能正常拉下来。
![image](https://user-images.githubusercontent.com/25702099/205570531-00f67de0-4eb7-4f4b-b2ca-2543368fd7c4.png)

- CodeSandBox案例的内容我看到了，是各种依赖写成的组件，那应该很容易嵌入到我现在的项目中。

**Comment by scarletfrank** [comment]
今早再看了下，发现问题了

CodeSandbox里的代码，无论是 UMD还是NPM，都是用以下依赖。我看现在库里的已经换名称了，你们看要不要改下。

```json
    "@alipay/gi-assets-advance": "2.18.0",
    "@alipay/gi-assets-basic": "2.22.0",
    "@alipay/gi-assets-scene": "2.7.1"
```
![image](https://user-images.githubusercontent.com/25702099/205777997-0503468b-8a83-4660-a1dc-a3437feee315.png)

**Comment by pomelo-nwu** [comment]
@scarletfrank 这个是之前localstorage缓存的问题，你清理下localstorage重新导出就好。

**Comment by scarletfrank** [comment]
> @scarletfrank 这个是之前localstorage缓存的问题，你清理下localstorage重新导出就好。

还真是...要 清理 [graphinsight.antgroup.com](https://graphinsight.antgroup.com/) 的缓存，CodeSandbox看到的就是新项目了
