### ISSUE TITLE
导出sdk包不能连接neo4j数据库 

### ISSUE THREAD

**Issue by vcfeelings** [antvis/GraphInsight#68]
我本地运行项目 连接neo4j 可以连接成功也可以查出来数据 然后 导出sdk本地运行不能查出来数据 
![lQLPJxhIPo-uoezNAfvNBSCwD70KCksh3YkDjIcPuYBJAA_1312_507](https://user-images.githubusercontent.com/31948883/206126773-0d9f3aaa-18ba-46ed-a32f-91cbabff7768.png)
![lQLPJxijMaAo4ezNASrNBK2wVcQyHjjGX44DjIcPuUCfAA_1197_298](https://user-images.githubusercontent.com/31948883/206126815-aee73c3d-6807-492f-b218-bfd8ae17cfd5.png)

导出sdk包 没有配置连接图数据库的地方

**Comment by vcfeelings** [comment]
导出的时候 带上这几个localStorage值就可以查了
![image](https://user-images.githubusercontent.com/31948883/206412287-3fcee357-55f8-4bf4-ab3c-917aedf7823b.png)
![image](https://user-images.githubusercontent.com/31948883/206412764-0376055e-3c70-4643-8c59-cdcf555367a8.png)

**Comment by BoyYangzai** [comment]
老哥我们正在修复～
