### ISSUE TITLE
导出选择“提供 NPM 包，支持 Tree Shaking，原生集成到 React 项目中” 放在react项目中报错

### ISSUE THREAD

**Issue by vcfeelings** [antvis/GraphInsight#69]
![image](https://user-images.githubusercontent.com/31948883/206164220-2913bc09-e391-49e5-a393-88b8b0b9f892.png)
pnpm 安装完所有需要的包 npm start 启动报错

**Comment by pomelo-nwu** [comment]
@vcfeelings 看起来都是类型的错误，先ignore然后跑起来？

**Comment by vcfeelings** [comment]
> @vcfeelings 看起来都是类型的错误，先ignore然后跑起来？

我尝试了 把ts里面的类型检测设置成any了 还是不行这些错误不报了 可以跑起来 但是是空白页 没有渲染出来东西

**Comment by vcfeelings** [comment]
> @vcfeelings 看起来都是类型的错误，先ignore然后跑起来？

我尝试了 把ts里面的类型检测设置成any了 还是不行这些错误不报了 可以跑起来 但是是空白页 没有渲染出来东西

**Comment by pomelo-nwu** [comment]
@vcfeelings 将`@antv/gi-sdk` 锁定版本到1.0.0

**Comment by vcfeelings** [comment]
> @vcfeelings 将`@antv/gi-sdk` 锁定版本到1.0.0
![image](https://user-images.githubusercontent.com/31948883/206338974-fbbd9988-f16c-4124-b11f-ea6642afe3ca.png)

已解决，vscode 代码格式化 代码换行了 导致 {/** @ts-ignore */} 没生效 调整不换行正常运行
