### ISSUE TITLE
导出选择“提供 NPM 包，支持 Tree Shaking，原生集成到 React 项目中”页面css错乱

### ISSUE THREAD

**Issue by vcfeelings** [antvis/GraphInsight#71]
导出sdk本地可以运行
![image](https://user-images.githubusercontent.com/31948883/206341959-a9878bfb-37cc-4d88-a2c9-8fa471ec2ff0.png)
但是得把这个
的light 变成字符串 源码导出是个变量 但是又找不到这个变量 不知道是不是这个主题的原因 导致页面css错乱
![image](https://user-images.githubusercontent.com/31948883/206342139-4d309b06-84f0-4b15-a1b0-8d619d70530d.png)
请求中暂时没有发现 未请求到的css

**Comment by vcfeelings** [comment]
导出的包中不知道为啥 不加载css文件
我这边手动导入css文件包解决了样式错乱
![image](https://user-images.githubusercontent.com/31948883/206394694-1b9d9834-2047-4b39-95ca-51e1d489f705.png)

**Comment by pomelo-nwu** [comment]
@vcfeelings  export const THEME_VALUE ='light' 确实是少了字符串，这个我们下个版本修复。
「导出的包中不知道为啥 不加载css文件」这个取决你项目的打包方式，一般情况下，默认都会加载es包中的less文件
